source 'https://rubygems.org'

gem 'rake'
gem 'iconv'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.9'
# use mysql
gem 'mysql2'
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# for memory cache
gem 'dalli'

# we use observers to expire the cache
gem 'rails-observers'

# 0.3.4 is bugged with api version (/api/v1)
# See : https://github.com/Apipie/apipie-rails/issues/353
gem 'apipie-rails', '= 0.3.3'

gem 'newrelic_rpm'

# cache digest
#gem 'cache_digests'

# For maintenance mode
gem 'turnout'

gem 'bootstrap-sass', '~> 3.2.0'
gem 'will_paginate'

gem 'omniauth-github'

gem 'sunspot_rails'
gem 'sunspot_solr'

gem 'browser'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-turbolinks'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

